name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        pod --version
        bundle install
        bundle exec pod --version
    - name: Run a one-line script
      run: ./scripts/pod_lib_lint.rb FirebaseCore.podspec --platforms=ios

