name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up
      run: |
        bundle install
        bundle exec pod --version
    - name: FirebaseCore
      run: ./scripts/pod_lib_lint.rb FirebaseCore.podspec --platforms=ios

